### PR TITLE
Add pagination and streaming

### LINKED ISSUE #67: Only able to retrieve first page of response
For API requests that have a large number of results, we're only returning the first page. Additionally because the headers are thrown away in the `process_response` call, we have no way to tell the user, "Hey, there are more pages to what you asked for."

Here's a `link` header from the call to `Tentacat.Repositories.list_users("jeffweiss")`
```elixir
  {"X-GitHub-Media-Type", "github.v3; format=json"},
  {"Link",
   "<https://api.github.com/user/818053/repos?page=2>; rel=\"next\", <https://api.github.com/user/818053/repos?page=5>; rel=\"last\""},
```

### PR DESCRIPTION
**Pull request by jeffweiss**
Close #67

### CODE REVIEW

**Comment by jeffweiss** [comment]
Hmm.. I'm using [URI.to_string](http://elixir-lang.org/docs/stable/elixir/URI.html#to_string/1), which is only available in Elixir 1.1+. @edgurgel, @duksis, thoughts on bumping minimum Elixir version to 1.1?

**Comment by jeffweiss** [comment]
Also just saw #69 merged, I should update to use those options as well. Standby...

**Comment by duksis** [comment]
first of all - thanks for the amazing contribution @jeffweiss !

In regards of bumping required Elixir version, I would prefer backporting [URI.to_string](https://github.com/elixir-lang/elixir/blob/7efc3847fa947d8711798e64b6af85c81ca4e191/lib/elixir/lib/uri.ex#L380..L411) for Elixir 1.0 than dropping the support for it. 
What's your take on this @edgurgel ?

**Comment by edgurgel** [comment]
I agree @duksis. Let's do this in 2 stages.

**Comment by jeffweiss** [comment]
Oh, we might not need to backport anything. It looks like `String.Chars.to_string(URI)` was defined in 1.0 even though `URI.to_string` was not. This might be a very simple change.

**Comment by jeffweiss** [comment]
\o/  --- If you have other changes you'd like me to make lemme know.

**Comment by duksis** [comment]
thanks! We will let you know when other changes will be needed. :wink:

**Comment by edgurgel** [comment]
:+1: We should release a new version with this contribution. I should give owner access yo you duksis. Do you have an e-mail registered with hex so I can add you? :)

**Comment by duksis** [comment]
@edgurgel should be duksis@gmail.com

**Comment by edgurgel** [comment]
```
$ mix hex.owner add tentacat duksis@gmail.com
Adding owner duksis@gmail.com to tentacat
```

:tada:

**Pull request merged**
