### PR TITLE
Add some apis

### PR DESCRIPTION
**Pull request by ghedamat**
* allow latest release
* repos/commits apis
* tags list api

I haven't added tests (yet) let me know if I should record some responses or if this is enough.

thanks for the project!

### CODE REVIEW

**Comment by edgurgel** [comment]
Thanks for the contribution! Can you check this PR and add similar tests? https://github.com/edgurgel/tentacat/pull/49

**Comment by duksis** [comment]
I'll record some responses for this, thanks @ghedamat

**Comment by ghedamat** [comment]
@duksis thanks for doing it for me!

**Comment by edgurgel** [comment]
Awesome :+1:

**Pull request merged**
