### PR TITLE
Bump Elixir and Erlang version

### PR DESCRIPTION
**Pull request by duksis**

### CODE REVIEW

**Comment by edgurgel** [comment]
Is there any reason to not support 1.0.* ? Cause if we are not using any special feature of 1.1 I think we should keep supporting 1.0 for some time. What do you think?

**Comment by edgurgel** [comment]
BTW! Welcome aboard as a contributor! :)

**Comment by duksis** [comment]
Thanks @edgurgel 
you are right we are not using any specific feature of 1.1.1 and should still support 1.0

I added 1.0 back, but there are some issues with Erlang 17.5 and Elixir 1.0.0 - I will look into it later today.

**Comment by duksis** [comment]
could not find a OTP 17 release that is working with both Elixir 1.1.1 and 1.0.0 so left only OTP 18.0 and 18.1
I guess thats fine as support for 17 will be dropped in Elixir 1.2 anyway

**Comment by edgurgel** [comment]
Fair enough!

**Pull request merged**
