### PR TITLE
EBKH/Add a repo to a team

### PR DESCRIPTION
**Pull request by EBKH**
Created the action to allow to add a repo to a team

### CODE REVIEW

**Comment by EBKH** [comment]
FYI, this action works with the dependencies updated, but the test keep failing

**Comment by EBKH** [comment]
@edgurgel Yes, that was what I intented. So I do rebase and avoid the updates again?

**Comment by edgurgel** [comment]
I would rebase and keep just the new code to add a repo to a team, if that's ok?

**Comment by EBKH** [comment]
@edgurgel Done :)

**Comment by edgurgel** [comment]
@EBKH awesome! Thank you! For the update of dependencies I think it's something with exvcr 🤔

**Pull request merged**
