### PR TITLE
client should be the first argument on all public functions

### PR DESCRIPTION
**Pull request by supernova32**
**This PR changes the signature of all public facing functions of the Tentacat API.**

Client should always be the first argument passed to the functions. Some functions had it this way, others had it at the end, others bang in the middle. This PR addresses this issue and makes everything consistent.

Having `client` be the first argument everywhere allows us to do

```elixir
%{access_token: token}
|> Tentacat.Client.new()
|> Tentacat.Contents.find_in("AlloyCI", "alloy_ci", ".alloy-ci.json", "long_sha")
|> elem(1)
|> parse_config()
```

_everywhere_.

Using pipes to process the information returned by the API makes it feel more natural, and I think it fits better with Elixir this way.

Also, code formatting.

### CODE REVIEW

**Comment by edgurgel** [comment]
I agree it should be consistent! And it should always be optional IMHO.

The reasons why client is not the first argument:

* It's optional as you can access most of GitHubs API without a token
* Elixir's first arguments are related to the module. So if you want a `User`, the username should be first argument. For example `Enum` receives an enumerable, `String` a string, etc

```elixir
user_name |> Tentacat.Users.find
```
Does this make sense? I'm keen to hear more about other users if they find it confusing also. Maybe following Elixir's convention is not a good idea for Tentacat?

**Comment by supernova32** [comment]
Thanks for the reply @edgurgel 

In the cases where the client is optional, you can leave it empty, and it will still work:

```elixir
 Tentacat.Users.find("supernova32")
"supernova32" |> Tentacat.Users.find()
```

Both examples I mentioned above work with the new code. The fact that almost all functions inside Tentacat define a `@spec` allows the compiler to pass the `String` where it belongs. In the case of `Users.find` that would be the second argument.

It works perfectly fine as well when there are more than 2 arguments;

```elixir
Tentacat.Pulls.list("edgurgel", "tentacat")
```

Is perfectly valid under the new code. Please give it a try 😄

I didn't change the optionality of the client argument (well, only in a couple of places where the API *would definitely* require an authenticated user), so everything should work as it should, with the added bonus that the `client` now comes first 👍

**Comment by bryanhuntesl** [comment]
I'll haven't viewed the implementation (on holidays) but I like the idea -
a consistent API will make many things easier to implement (the author
gives one example, but I am sure there are many).

There is also the question of the public  methods where no authentication
is required - In their case, rate limiting still applies.

I suggest it would be good practice to always initialise with a user
structure, even if it is empty: one can always revisit the initialisation
site at a later time and add the credentials if needed.

**Comment by supernova32** [comment]
@outofambit there is nothing preventing you from _not_ piping the client. You can still instantiate your client first (or pass it as an argument to another function, like in your example) and then use it as the first argument in all your Tentacat calls. You can even use the `client` variable in a pipe for multiple calls like so:

```elixir
client = Tentacat.Client.new(%{access_token: token})

client |> Tentacat.Pulls.list("edgurgel", "tentacat")

client |> Tentacat.Contents.find_in("AlloyCI", "alloy_ci", ".alloy-ci.json", "master")
```

The main point of the PR is _not_ to enforce passing the client in a pipe. It is to bring conciseness to Tentacat's API. Having the client always be the first argument will avoid a lot of confusion, specially for calls like `(owner, repo, client, options, params)`. I need to always look up the function signature before calling it, because I have no idea in which place the client should go. Why?

Being able to do it with a pipe is just icing on the cake.

**Comment by outofambit** [comment]
@supernova32 ah I see what you're saying. I totally agree we should standardize it and I like the argument for putting it first! I actually think piping the client like `client |> Tentacat.Pulls.list("edgurgel", "tentacat")`  makes the API call itself easier to read!

**Comment by supernova32** [comment]
@edgurgel any chance we can get this merged? the consensus seems to be that these changes are helpful.

**Comment by edgurgel** [comment]
@supernova32 I will play with your branch this weekend and see how it goes! Thanks for the PR

**Comment by edgurgel** [comment]
> Both examples I mentioned above work with the new code. The fact that almost all functions inside Tentacat define a @spec allows the compiler to pass the String where it belongs. In the case of Users.find that would be the second argument.

Are you sure? AFAIK @spec is not used by the compiler directly, but for dialyzer

I think it's working just because that specific function (find) has an optional Client as the second argument:

```elixir
  def find(client \\ %Client{}, user) do
```

**Comment by edgurgel** [comment]
We need to update the README (possibly pointing that this is the way to interact from now on etc?). 

I will bump the version to `1.0.0` and consider this the stable version.

**Pull request merged**
