### PR TITLE
Update Elixir and dependencies [help needed]

### PR DESCRIPTION
**Pull request by EBKH**
Everything seems to work (been using [my fork](https://github.com/valiot/tentacat/) for a while now), but almost all tests are failed. I've updated all deps, try with JSX, Jason and Poison, but I hadn't been able to locate and fix the issues with the test

### CODE REVIEW

**Comment by edgurgel** [comment]
Hey thanks for the PR! 

Do we have a good reason to bump the elixir requirement to 1.7?

**Comment by EBKH** [comment]
I don't really know, the reason behind me updating is to avoid downgrading Httpoison from 1.3 to 0.8 in my project

**Comment by edgurgel** [comment]
Yeah HTTPoison makes sense to be upgraded. I was curious about the elixir requirement 🤔

**Comment by edgurgel** [comment]
exvcr seems to not match the correct cassette. Not sure why 🤔

**Comment by edgurgel** [comment]
Apparently solved by #181

**Pull request closed without merging**
