### PR TITLE
Fix function clauses error when Httpoison 1.5

### PR DESCRIPTION
**Pull request by terriblecodebutwork**
It's a quick fix for using httpoison >= 1.5. All tests passed.

### CODE REVIEW

**Comment by iautom8things** [comment]
Just came here to see if this was reported 👍

**Comment by edgurgel** [comment]
Thank you ! 🎉

**Comment by iautom8things** [comment]
Thank you, both!  Do you have a sense what version release this will make this into?

**Comment by edgurgel** [comment]
@iautom8things , I've just released a new version! 1.6.0 is out

**Pull request merged**
