### PR TITLE
Add support to custom handling of API response.

### PR DESCRIPTION
**Pull request by iurifq**

### CODE REVIEW

**Comment by duksis** [comment]
@edgurgel I haven't seen the need for it yet, but does not seem to interfere with anything, tests pass and could come handy. WDYT?

**Comment by edgurgel** [comment]
I would like to understand what's a good use case and also maybe a test?

(I don't know how this PR didn't call my attention)

Sorry, @iurifq :D

**Comment by iurifq** [comment]
I actually don't even remember why I created this. There was a use case at the time, but I don't know if it's still valid. It's up to you guys

**Comment by iurifq** [comment]
Sorry, I accidentally closed it. I hate this button positioning :disappointed:

**Comment by edgurgel** [comment]
I would say: reopen if we find an use case. :+1:

**Comment by iurifq** [comment]
:+1:

**Pull request closed without merging**
