### PR TITLE
return {code,body,response} in all requests

### PR DESCRIPTION
**Pull request by bryanhuntesl**

### CODE REVIEW

**Comment by edgurgel** [comment]
Thanks for the great work! I Will release a new minor version with the current master then merge your PR and work towards documenting the breaking changes so that people can easily update! 🎉

**Comment by bryanhuntesl** [comment]
Sweet - thanks @edgurgel - all I have to do now is figured out how to manage the rate limiting (harder task).

**Comment by bryanhuntesl** [comment]
Perhaps we could bundle a couple of utility macros or helpers to more easily extract the payload? 

Like:

```
success?({code,payload,response}) -> true || false
result!({code,payload,response}) -> payload() || throw exception()
limit?({code,payload,response}) -> limit() || throw exception()
```

**Comment by bryanhuntesl** [comment]
Hey @edgurgel - just going over open P/R's - it's been a while - what do you think, is it good to merge?

**Comment by edgurgel** [comment]
@bryanhuntesl, yes I think we are pretty close. I would like to know why this code is not reached or it seems to not be reachable 🤔 : 

```
never seems to hit this block...
+      # x when is_tuple(x) -> x
```

 Thank you again for starting this 🎉

**Comment by bryanhuntesl** [comment]
@edgurgel - looking further into it that function `request_with_pagination/3` is only invoked when a get is issued with pagination option set to `:manual`

https://github.com/bryanhuntesl/tentacat/blob/54d16654b79309dafdabf173ed9cf1b5adc45c67/lib/tentacat.ex#L59

This is in turn tested by:

https://github.com/bryanhuntesl/tentacat/blob/54d16654b79309dafdabf173ed9cf1b5adc45c67/test/repositories_test.exs#L41-L48

All tests pass, should we just delete it? I only left it there in case you knew of some specific reason that code existed (I couldn't see a reason for it)

**Comment by edgurgel** [comment]
Yeah if there's no code reaching it let's just delete it! Thanks for investigating 👍

**Comment by bryanhuntesl** [comment]
Ok. I'll delete and correct the merge conflict

**Comment by bryanhuntesl** [comment]
Should be good to go - have merged and fixed new tests from master branch

**Comment by edgurgel** [comment]
We should get a new version soon. Thanks for the PR! 🎉

**Comment by bryanhuntesl** [comment]
Excellent - great working with you, you've been a champ.

**Pull request merged**
