### PR TITLE
support custom endpoint

### PR DESCRIPTION
**Pull request by Joe-noh**
This pull request make tentacat to support custom endpoint.
The main purpose is to access github enterprise API.

- Changes
  - add new item `endpoint` to `Tentacat.Client` struct.
  - implement `Tentacat.Client.new/1` and `Tentacat.Client.new/2`.

I'd appreciate any feedback. Thank you.

### CODE REVIEW

**Comment by edgurgel** [comment]
That's really interesting. Do you mind adding a section to README with an example for people using a custom base URL for enterprise API?

**Comment by Joe-noh** [comment]
Updated !!

**Comment by edgurgel** [comment]
Thanks! I will merge and release a new version soon!

**Comment by edgurgel** [comment]
This was released as part of https://hex.pm/packages/tentacat/0.2.0

**Comment by Joe-noh** [comment]
Thank you! :smile:

**Pull request merged**
