### PR TITLE
Adds test coverage badge to the projects

### PR DESCRIPTION
**Pull request by duksis**
First of all thanks for creating this great project.

As I'm planing to use it in one of my upcoming side projects I will need to extend the current functionality.
While doing that I would like to increase the test coverage as this is something that makes me a bit worried.
This pull request would be the first step to increase the coverage. awareness :)

### CODE REVIEW

**Comment by edgurgel** [comment]
We would love to increase the coverage (https://github.com/edgurgel/tentacat/issues/17). Send them and we will merge :D

**Comment by duksis** [comment]
travis is failing as there is no https://coveralls.io project under `edgurgel/tentacat`, if you would create it should be green again

**Comment by edgurgel** [comment]
I just created it. I will rebuild it

**Comment by edgurgel** [comment]
9%! :no_mouth:

**Pull request merged**
