### PR TITLE
Add `httpoison` requirement to readme

### PR DESCRIPTION
**Pull request by tmikoss**
Going through the examples in readme, I got a `httpoison`-related error message. Searching led me to a similar problem and a working solution on StackOverflow: http://stackoverflow.com/questions/31208923/hackney-fails-to-make-request-to-server

### CODE REVIEW

**Comment by edgurgel** [comment]
It's not needed to add `httpoison` but `tentacat`. If you add `:tentacat`  to the applications list it should work as httpoison is declared on tentacat's application list. Can you amend the commit replacing httpoison with tentacat?

Thank you for the PR.

**Comment by tmikoss** [comment]
I've ammended the commit, but while doing so I noticed the call to `Tentacat.start` that I had previously overlooked.

I'm new to Elixir - is manually starting library processes a common practice? My background is mainly Ruby, so I was expecting it to work without any additional steps :)

If that is a common way of doing things, please feel free to close this PR.

**Comment by edgurgel** [comment]
You are correct. That Tentacat.start is gone a long time ago

**Comment by edgurgel** [comment]
Thank you! :tada:

**Pull request merged**
