### PR TITLE
update path to fetch installation token

### PR DESCRIPTION
**Pull request by iffyuva**
Since https://developer.github.com/v3/apps/ are still in beta (life sucks!), they have changed api to fetch tokens once again.

If we do `Tentacat.App.Installations.list_mine(t)`, response is something like this:

```js
{200,
 [
   %{
     "access_tokens_url" => "https://api.github.com/installations/929200/access_tokens",
     "account" => %{
       "avatar_url" => "https://avatars0.githubusercontent.com/u/1137275?v=4",
       "snip" => "<all-other-urls>"
     },
     "app_id" => 16094,
     "created_at" => "2019-04-08T01:55:18.000Z",
     "events" => ["commit_comment", "create", "delete", "deployment",
      "deployment_status", "member", "membership", "pull_request", "push"],
     "id" => 929200,
     "permissions" => %{
       "contents" => "read",
       "deployments" => "write",
       "members" => "read",
       "metadata" => "read",
       "organization_projects" => "read",
       "pull_requests" => "read"
     },
     "repositories_url" => "https://api.github.com/installation/repositories",
     "repository_selection" => "selected",
     "single_file_name" => nil,
     "target_id" => 2237275,
     "target_type" => "Organization",
     "updated_at" => "2019-04-08T01:55:18.000Z"
   }
 ],
 %HTTPoison.Response{
   body: [
     %{
       "snip" => "all-content"
     }
   ],
   headers: [
     {"Date", "Mon, 08 Apr 2019 02:25:59 GMT"},
     {"Content-Type", "application/json; charset=utf-8"},
     {"Content-Length", "9751"},
     {"Server", "GitHub.com"},
     {"Status", "200 OK"},
     {"Cache-Control", "public, max-age=60, s-maxage=60"},
     {"Vary", "Accept"},
     {"X-GitHub-Media-Type", "github.machine-man-preview; format=json"},
     {"X-GitHub-Request-Id", "FA9F:91AE:26D9C84:2EE1D8C:5CAAB12E"}
   ],
   request_url: "https://api.github.com/app/installations",
   status_code: 200
 }}
```

So, if we check `access_tokens_url` key, its value is `https://api.github.com/installations/929200/access_tokens`, ie path is not prepended with `/app`. This PR fixes that!

### CODE REVIEW

**Comment by edgurgel** [comment]
Hey! Thanks for the contribution :D I think we need to update the cassette for the tests!

**Comment by iffyuva** [comment]
😿

**Comment by iffyuva** [comment]
@edgurgel fixed!

**Comment by jakewilkins** [comment]
👋 Hey y'all

Unfortunately the endpoint backing `Tentacat.App.Installations.list_mine` is sending a [deprecated](https://developer.github.com/changes/2018-08-16-renaming-and-deprecation-of-github-app-installation-access-token-route/) URL here.

The path that is currently in Tentacat master that contains the `/app` prefix is the correct path.

Apologies for this inconsistency, this response is a bug and we're updating it to send the correct path ASAP.

**Comment by iffyuva** [comment]
@jakewilkins oh man! Our app hits url with no `/app` prepended, and the code is in production already. Should I revert that change?

**Comment by jakewilkins** [comment]
@iffyuva yes, eventually `installations/<id>/access_tokens` (no `/app` prefix) will be disabled. We'll update the [developer blog](https://developer.github.com/changes/) when we figure out the timeline.

**Comment by iffyuva** [comment]
@jakewilkins thanks for the update. I will revert this change today, and see if that works. Thanks.

**Pull request closed without merging**
