### PR TITLE
Add missing filter functions

### LINKED ISSUE #80: URL Parameters
Trying to use `Tentacat.Issues.list_all` passing a `since` parameter like the docs allow but it seems to be impossible... Several other functions seem to not allow this capability.

### PR DESCRIPTION
**Pull request by mgwidmann**
Fixes #80

### CODE REVIEW

**Comment by duksis** [comment]
Thanks @mgwidmann - could you add tests for these?

**Comment by mgwidmann** [comment]
I've not use VCR before w/ Elixir, to add these new endpoints do I need to put my own credentials in so it will record the cassettes correctly?

I keep getting this error:
```
** (ExVCR.RequestNotMatchError) Request did not match with any one in the current cassette: test/fixture/vcr_cassettes/commits#filter.json.
     Delete the current cassette with [mix vcr.delete] and re-record.
```

There is no such task and I'm a bit confused at the moment 😕 ...

**Comment by duksis** [comment]
@mgwidmann yes you would need to use some valid credentials - or a client without any token what should work for public reads.

The mix task for deleting cassettes is not available, but this task just deletes fixture files what you can do manually. Here for example is the fixture file for `Tentacat.Commits.list/3` https://github.com/edgurgel/tentacat/blob/master/test/fixture/vcr_cassettes/commits%23list.json

When you are working on a already existing test file I would suggest you to replace the `@client` with your custom client on a test level `Tentacat.Client.new(%{access_token: "yourtokencomeshere"})`
and after your done with recording just replace the real credentials with fake in the test and recorded response.

Hope this makes it a little bit clearer - let me know if that's not the case. :)

**Comment by mgwidmann** [comment]
I'll give that a try, thanks

**Comment by mgwidmann** [comment]
Sorry it took so long! Tests are added now!

**Comment by duksis** [comment]
big thanks @mgwidmann !

**Pull request merged**
